<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Native" Version="12.1.3" />
    <PackageVersion Include="ktsu.Essentials" Version="2.6.4" />
    <PackageVersion Include="ktsu.Essentials.FileSystemProviders.Native" Version="2.6.4" />
    <PackageVersion Include="ktsu.Essentials.PersistenceProviders.ConfigHome" Version="2.6.4" />
    <PackageVersion Include="ktsu.Essentials.PersistenceProviders.InMemory" Version="2.6.4" />
    <PackageVersion Include="ktsu.Essentials.SerializationProviders.Json" Version="2.6.4" />
    <PackageVersion Include="Polyfill" Version="11.4.0" />
  </ItemGroup>
</Project>
